# -*- coding: utf-8 -*-
"""LunarLander.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mx_gUpqdtrn1h0HIKZ5cTdEKwZ0ilhV3
"""

!pip cache purge
!apt update && apt install xvfb
!pip install gym-notebook-wrapper
!pip install cmake
!pip install swig
!pip install gym[classic_control]==0.25.2
!pip install gym[box2d]==0.25.2
!pip install opencv-python-headless
!pip install stable-baselines3==2.1.0
!pip install pyglet==1.5.27
!pip install 'shimmy>=0.2.1

import gym
from stable_baselines3 import PPO

model = PPO("MlpPolicy", "LunarLander-v2", verbose=1, ent_coef=0.01, n_steps=2048)
model.learn(total_timesteps=int(1e5), log_interval=10)
model.save("model")

import gnwrapper

env = gnwrapper.Monitor(gym.make("LunarLander-v2", render_mode='rgb_array'),directory="./video/")

observation = env.reset()
total_reward = 0
for i in range(1200):
    action, _states = model.predict(observation)
    observation, reward, terminated, truncated = env.step(action)
    total_reward += reward

env.display()
print(f"Total reward: {total_reward}")

"""# Nowa sekcja"""